Implementation for Java
ollef/Fuse.JSON pull request #1
Opened 2017-02-02 11:58 UTC by nexoone

2017-02-02 12:06 UTC, ollef requested changes
Hey, and thanks!

Looks great to me! I added some minor nits as comments.

2017-02-02 12:06 UTC, ollef commented on JavaObject.uno
> +					"java.lang.Object",
Something's up with the indentation here.

2017-02-02 12:06 UTC, ollef commented on JavaObject.uno
> +		public Java.Object Case(string str) @{ return (String) str; @}
This cast is not necessary.

2017-02-02 12:06 UTC, ollef commented on JavaObject.uno
> +		public Java.Object Case(double num) @{ return (double) num; @}
Is this cast necessary?

2017-02-02 12:06 UTC, ollef commented on JavaObject.uno
> +		public Java.Object Case(bool b) @{ return (boolean) b; @}
Is this cast necessary?

2017-02-02 12:06 UTC, ollef commented on JavaObject.uno
> +			debug_log("UNO - ToJavaObject - handle array");
Please remove this.

2017-02-02 12:06 UTC, ollef commented on JavaObject.uno
> +			debug_log("UNO - dict: " + dict);
Remove.

2017-02-02 12:06 UTC, ollef commented on JavaObject.uno
> +		extern(Android) void SetDictValue(Java.Object dictHandle, string key, Java.Object value)
Consider renaming to e.g. `SetMapValue` to match the Java names better.

2017-02-02 12:06 UTC, ollef commented on JavaObject.uno
> +			debug_log("UNO - NewHashMap");
Remove.

2017-02-09 15:58 UTC, nexoone commented on JavaObject.uno
> +		extern(Android) void SetDictValue(Java.Object dictHandle, string key, Java.Object value)
right...good point

2017-02-09 15:58 UTC, nexoone commented on JavaObject.uno
> +			debug_log("UNO - NewHashMap");
again .... :-)

2017-02-09 15:58 UTC, nexoone commented on JavaObject.uno
> +			debug_log("UNO - dict: " + dict);
yes sure

2017-02-09 15:58 UTC, nexoone commented on JavaObject.uno
> +			debug_log("UNO - ToJavaObject - handle array");
yes sure

2017-02-09 15:58 UTC, nexoone commented on JavaObject.uno
> +		public Java.Object Case(bool b) @{ return (boolean) b; @}
I don't know .... i do not tested it without the cast

2017-02-09 15:58 UTC, nexoone commented on JavaObject.uno
> +		public Java.Object Case(double num) @{ return (double) num; @}
I don't know .... i do not tested it without the cast

2017-02-09 15:58 UTC, nexoone commented on JavaObject.uno
> +		public Java.Object Case(string str) @{ return (String) str; @}
correct

2017-02-09 15:58 UTC, nexoone commented on JavaObject.uno
> +					"java.lang.Object",
ohh ok....

2017-02-09 18:33 UTC, ollef commented
Thanks!

2017-02-09 18:33 UTC, merged